version: '3'
services:
  app:
    container_name: webapp
    restart: always
    build: .
    ports:
      - '3004:3004'
    networks:
      - network
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    container_name: checkout-db
    volumes:
      - ./checkout-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - network

networks:
  network:
    driver: bridge